#PLGE0
set_property LOC AB17 [get_ports clk_25M_out0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_25M_out0]

set_property LOC AF13 [get_ports phy_rst_n0]
set_property IOSTANDARD LVCMOS33 [get_ports phy_rst_n0]

set_property LOC AG12 [get_ports gmii0_txd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_txd[0]]
set_property LOC AF12 [get_ports gmii0_txd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_txd[1]]
set_property LOC AE12 [get_ports gmii0_txd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_txd[2]]
set_property LOC AD13 [get_ports gmii0_txd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_txd[3]]
set_property LOC AC13 [get_ports gmii0_txd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_txd[4]]
set_property LOC AC12 [get_ports gmii0_txd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_txd[5]]
set_property LOC AB12 [get_ports gmii0_txd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_txd[6]]
set_property LOC AA14 [get_ports gmii0_txd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_txd[7]]

set_property LOC AG15 [get_ports gmii0_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_tx_en]
set_property LOC AF14 [get_ports gmii0_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_tx_clk]
set_property LOC AB15 [get_ports gmii0_tx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_tx_er]

set_property LOC AF17 [get_ports gmii0_rxd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_rxd[0]]
set_property LOC AD15 [get_ports gmii0_rxd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_rxd[1]]
set_property LOC AH17 [get_ports gmii0_rxd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_rxd[2]]
set_property LOC AD14 [get_ports gmii0_rxd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_rxd[3]]
set_property LOC AK15 [get_ports gmii0_rxd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_rxd[4]]
set_property LOC AJ15 [get_ports gmii0_rxd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_rxd[5]]
set_property LOC AH14 [get_ports gmii0_rxd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_rxd[6]]
set_property LOC AG14 [get_ports gmii0_rxd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_rxd[7]]

set_property LOC AG17 [get_ports gmii0_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_rx_clk]
set_property LOC AE17 [get_ports gmii0_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_rx_dv]
set_property LOC AH13 [get_ports gmii0_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_rx_er]

set_property LOC AD16 [get_ports mdio0_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports mdio0_mdio_io]
set_property LOC AE18 [get_ports mdio0_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio0_mdc]

set_property LOC AF18 [get_ports gmii0_gtx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_gtx_clk]

set_property LOC AE13 [get_ports gmii0_gtx_in]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_gtx_in]

#PLGE1
set_property LOC AB22 [get_ports clk_25M_out1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_25M_out1]

set_property LOC AK21 [get_ports phy_rst_n1]
set_property IOSTANDARD LVCMOS33 [get_ports phy_rst_n1]

set_property LOC AH22 [get_ports gmii1_txd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[0]]
set_property LOC AJ21 [get_ports gmii1_txd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[1]]
set_property LOC AG22 [get_ports gmii1_txd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[2]]
set_property LOC AJ20 [get_ports gmii1_txd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[3]]
set_property LOC AH21 [get_ports gmii1_txd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[4]]
set_property LOC AK20 [get_ports gmii1_txd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[5]]
set_property LOC AJ19 [get_ports gmii1_txd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[6]]
set_property LOC AH19 [get_ports gmii1_txd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[7]]

set_property LOC AK22 [get_ports gmii1_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_tx_en]
set_property LOC AE22 [get_ports gmii1_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_tx_clk]
set_property LOC AG19 [get_ports gmii1_tx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_tx_er]

set_property LOC AC24 [get_ports gmii1_rxd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[0]]
set_property LOC AD24 [get_ports gmii1_rxd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[1]]
set_property LOC AE23 [get_ports gmii1_rxd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[2]]
set_property LOC AG25 [get_ports gmii1_rxd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[3]]
set_property LOC AF24 [get_ports gmii1_rxd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[4]]
set_property LOC AG24 [get_ports gmii1_rxd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[5]]
set_property LOC AH23 [get_ports gmii1_rxd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[6]]
set_property LOC AF23 [get_ports gmii1_rxd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[7]]

set_property LOC AG21 [get_ports gmii1_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rx_clk]
set_property LOC AB24 [get_ports gmii1_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rx_dv]
set_property LOC AJ23 [get_ports gmii1_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rx_er]

set_property LOC AF19 [get_ports mdio1_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports mdio1_mdio_io]
set_property LOC AE21 [get_ports mdio1_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio1_mdc]

set_property LOC AK17 [get_ports gmii1_gtx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_gtx_clk]

set_property LOC AD23 [get_ports gmii1_gtx_in]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_gtx_in]

#PLGE2
set_property LOC P21 [get_ports clk_25M_out2]
set_property IOSTANDARD LVCMOS33 [get_ports clk_25M_out2]

set_property LOC P25 [get_ports phy_rst_n2]
set_property IOSTANDARD LVCMOS33 [get_ports phy_rst_n2]

set_property LOC U27 [get_ports gmii2_txd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[0]]
set_property LOC P24 [get_ports gmii2_txd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[1]]
set_property LOC P23 [get_ports gmii2_txd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[2]]
set_property LOC V23 [get_ports gmii2_txd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[3]]
set_property LOC R23 [get_ports gmii2_txd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[4]]
set_property LOC V22 [get_ports gmii2_txd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[5]]
set_property LOC U21 [get_ports gmii2_txd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[6]]
set_property LOC U22 [get_ports gmii2_txd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[7]]

set_property LOC W26 [get_ports gmii2_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_tx_en]
set_property LOC R25 [get_ports gmii2_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_tx_clk]
set_property LOC T22 [get_ports gmii2_tx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_tx_er]

set_property LOC T30 [get_ports gmii2_rxd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[0]]
set_property LOC T29 [get_ports gmii2_rxd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[1]]
set_property LOC T28 [get_ports gmii2_rxd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[2]]
set_property LOC U30 [get_ports gmii2_rxd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[3]]
set_property LOC U29 [get_ports gmii2_rxd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[4]]
set_property LOC W30 [get_ports gmii2_rxd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[5]]
set_property LOC V29 [get_ports gmii2_rxd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[6]]
set_property LOC W29 [get_ports gmii2_rxd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[7]]

set_property LOC R27 [get_ports gmii2_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rx_clk]
set_property LOC T27 [get_ports gmii2_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rx_dv]
set_property LOC W28 [get_ports gmii2_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rx_er]

set_property LOC R21 [get_ports mdio2_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports mdio2_mdio_io]
set_property LOC R22 [get_ports mdio2_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio2_mdc]

set_property LOC W24 [get_ports gmii2_gtx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_gtx_clk]

set_property LOC U25 [get_ports gmii2_gtx_in]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_gtx_in]

#PL external CLKs
set_property LOC W8 [get_ports refclk_p]
create_clock -name refclk_p -period 6.4 [get_ports refclk_p]

set_property LOC H9 [get_ports free_200M_clk_p]
set_property IOSTANDARD LVDS [get_ports free_200M_clk_p]
create_clock -name free_200M_clk_p -period 5 [get_ports free_200M_clk_p]

#PL_SFP0
set_property LOC W4 [get_ports sfp0_txp]
set_property LOC W3 [get_ports sfp0_txn]
set_property LOC Y6 [get_ports sfp0_rxp]
set_property LOC Y5 [get_ports sfp0_rxn]

#PL_SFP1
set_property LOC AB2 [get_ports sfp1_txp]
set_property LOC AB1 [get_ports sfp1_txn]
set_property LOC AC4 [get_ports sfp1_rxp]
set_property LOC AC3 [get_ports sfp1_rxn]

set_property LOC AJ16 [get_ports sfp0_disable_out]
set_property IOSTANDARD LVCMOS33 [get_ports sfp0_disable_out]
set_property LOC AK16 [get_ports sfp1_disable_out]
set_property IOSTANDARD LVCMOS33 [get_ports sfp1_disable_out]
