#PLGE0(use PSGE00 EMIO)
# phy reset will use GPIO@PS(MIO22)
#set_property LOC A14 [get_ports phy_rst_n0]
#set_property IOSTANDARD LVCMOS33 [get_ports phy_rst_n0]

set_property LOC B16 [get_ports PSGE0_txd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_txd[0]]
set_property LOC A17 [get_ports PSGE0_txd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_txd[1]]
set_property LOC A18 [get_ports PSGE0_txd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_txd[2]]
set_property LOC A16 [get_ports PSGE0_txd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_txd[3]]
set_property LOC B17 [get_ports PSGE0_txd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_txd[4]]
set_property LOC A19 [get_ports PSGE0_txd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_txd[5]]
set_property LOC A21 [get_ports PSGE0_txd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_txd[6]]
set_property LOC B20 [get_ports PSGE0_txd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_txd[7]]

set_property LOC B15 [get_ports PSGE0_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_tx_en]
set_property LOC D18 [get_ports PSGE0_TX_CLK_PHY]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_TX_CLK_PHY]
set_property LOC B21 [get_ports PSGE0_tx_er]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_tx_er]

set_property LOC G16 [get_ports PSGE0_rxd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_rxd[0]]
set_property LOC G17 [get_ports PSGE0_rxd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_rxd[1]]
set_property LOC G15 [get_ports PSGE0_rxd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_rxd[2]]
set_property LOC F17 [get_ports PSGE0_rxd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_rxd[3]]
set_property LOC F16 [get_ports PSGE0_rxd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_rxd[4]]
set_property LOC E18 [get_ports PSGE0_rxd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_rxd[5]]
set_property LOC E16 [get_ports PSGE0_rxd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_rxd[6]]
set_property LOC D17 [get_ports PSGE0_rxd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_rxd[7]]

set_property LOC C17 [get_ports PSGE0_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_rx_clk]
set_property LOC D16 [get_ports PSGE0_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_rx_dv]
set_property LOC E15 [get_ports PSGE0_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_rx_er]

set_property LOC J17 [get_ports PSMDIO0_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports PSMDIO0_mdio_io]
set_property LOC J21 [get_ports PSMDIO0_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports PSMDIO0_mdc]

set_property LOC C18 [get_ports PSGE0_gtxclk]
set_property IOSTANDARD LVCMOS33 [get_ports PSGE0_gtxclk]

set_property IODELAY_GROUP tri_mode_ethernet_mac_iodelay_grp [get_cells axi_ethernet_idelay_ctrl]

#PLGE1
set_property LOC R16 [get_ports phy_rst_n1]
set_property IOSTANDARD LVCMOS33 [get_ports phy_rst_n1]

set_property LOC U21 [get_ports gmii1_txd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[0]]
set_property LOC U22 [get_ports gmii1_txd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[1]]
set_property LOC T22 [get_ports gmii1_txd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[2]]
set_property LOC V22 [get_ports gmii1_txd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[3]]
set_property LOC W21 [get_ports gmii1_txd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[4]]
set_property LOC AA22 [get_ports gmii1_txd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[5]]
set_property LOC W22 [get_ports gmii1_txd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[6]]
set_property LOC AA21 [get_ports gmii1_txd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[7]]

set_property LOC T21 [get_ports gmii1_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_tx_en]
set_property LOC Y18 [get_ports gmii1_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_tx_clk]
set_property LOC AB22 [get_ports gmii1_tx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_tx_er]

set_property LOC U17 [get_ports gmii1_rxd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[0]]
set_property LOC U20 [get_ports gmii1_rxd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[1]]
set_property LOC U19 [get_ports gmii1_rxd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[2]]
set_property LOC V19 [get_ports gmii1_rxd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[3]]
set_property LOC V20 [get_ports gmii1_rxd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[4]]
set_property LOC W20 [get_ports gmii1_rxd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[5]]
set_property LOC V18 [get_ports gmii1_rxd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[6]]
set_property LOC Y21 [get_ports gmii1_rxd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[7]]

set_property LOC Y19 [get_ports gmii1_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rx_clk]
set_property LOC V17 [get_ports gmii1_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rx_dv]
set_property LOC Y20 [get_ports gmii1_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rx_er]

set_property LOC R19 [get_ports mdio1_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports mdio1_mdio_io]
set_property LOC T19 [get_ports mdio1_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio1_mdc]

set_property LOC AA18 [get_ports gmii1_gtx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_gtx_clk]

#PLGE2
set_property LOC R20 [get_ports phy_rst_n2]
set_property IOSTANDARD LVCMOS33 [get_ports phy_rst_n2]

set_property LOC K21 [get_ports gmii2_txd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[0]]
set_property LOC L22 [get_ports gmii2_txd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[1]]
set_property LOC L21 [get_ports gmii2_txd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[2]]
set_property LOC N20 [get_ports gmii2_txd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[3]]
set_property LOC M22 [get_ports gmii2_txd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[4]]
set_property LOC M21 [get_ports gmii2_txd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[5]]
set_property LOC K20 [get_ports gmii2_txd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[6]]
set_property LOC N22 [get_ports gmii2_txd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[7]]

set_property LOC P21 [get_ports gmii2_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_tx_en]
set_property LOC L18 [get_ports gmii2_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_tx_clk]
set_property LOC P22 [get_ports gmii2_tx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_tx_er]

set_property LOC P18 [get_ports gmii2_rxd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[0]]
set_property LOC P20 [get_ports gmii2_rxd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[1]]
set_property LOC P17 [get_ports gmii2_rxd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[2]]
set_property LOC N19 [get_ports gmii2_rxd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[3]]
set_property LOC N18 [get_ports gmii2_rxd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[4]]
set_property LOC N17 [get_ports gmii2_rxd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[5]]
set_property LOC M17 [get_ports gmii2_rxd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[6]]
set_property LOC M16 [get_ports gmii2_rxd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[7]]

set_property LOC K19 [get_ports gmii2_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rx_clk]
set_property LOC L17 [get_ports gmii2_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rx_dv]
set_property LOC J16 [get_ports gmii2_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rx_er]

set_property LOC T18 [get_ports mdio2_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports mdio2_mdio_io]
set_property LOC R21 [get_ports mdio2_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio2_mdc]

set_property LOC L19 [get_ports gmii2_gtx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_gtx_clk]
