#PLGE1
set_property LOC AB26 [get_ports clk_25M_out1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_25M_out1]

set_property LOC AK27 [get_ports phy_rst_n1]
set_property IOSTANDARD LVCMOS33 [get_ports phy_rst_n1]

set_property LOC AF28 [get_ports gmii1_txd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[0]]
set_property LOC AK28 [get_ports gmii1_txd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[1]]
set_property LOC AJ28 [get_ports gmii1_txd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[2]]
set_property LOC AK26 [get_ports gmii1_txd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[3]]
set_property LOC AJ26 [get_ports gmii1_txd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[4]]
set_property LOC AH26 [get_ports gmii1_txd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[5]]
set_property LOC AE26 [get_ports gmii1_txd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[6]]
set_property LOC AD26 [get_ports gmii1_txd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[7]]

set_property LOC AH27 [get_ports gmii1_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_tx_en]
set_property LOC AC28 [get_ports gmii1_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_tx_clk]
set_property LOC AC27 [get_ports gmii1_tx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_tx_er]

set_property LOC AD30 [get_ports gmii1_rxd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[0]]
set_property LOC AD29 [get_ports gmii1_rxd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[1]]
set_property LOC AE30 [get_ports gmii1_rxd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[2]]
set_property LOC AD28 [get_ports gmii1_rxd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[3]]
set_property LOC AF29 [get_ports gmii1_rxd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[4]]
set_property LOC AF30 [get_ports gmii1_rxd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[5]]
set_property LOC AH29 [get_ports gmii1_rxd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[6]]
set_property LOC AJ30 [get_ports gmii1_rxd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[7]]

set_property LOC AE27 [get_ports gmii1_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rx_clk]
set_property LOC AB30 [get_ports gmii1_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rx_dv]
set_property LOC AJ29 [get_ports gmii1_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rx_er]

set_property LOC AC29 [get_ports mdio1_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports mdio1_mdio_io]
set_property LOC AC26 [get_ports mdio1_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio1_mdc]

set_property LOC AB27 [get_ports gmii1_gtx_in]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_gtx_in]
create_clock -name gmii1_gtx_in -period 8.0 [get_ports gmii1_gtx_in]

set_property LOC AG26 [get_ports gmii1_gtx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_gtx_clk]

#PLGE2
set_property LOC AB17 [get_ports clk_25M_out2]
set_property IOSTANDARD LVCMOS33 [get_ports clk_25M_out2]

set_property LOC AF13 [get_ports phy_rst_n2]
set_property IOSTANDARD LVCMOS33 [get_ports phy_rst_n2]

set_property LOC AG12 [get_ports gmii2_txd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[0]]
set_property LOC AF12 [get_ports gmii2_txd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[1]]
set_property LOC AE12 [get_ports gmii2_txd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[2]]
set_property LOC AD13 [get_ports gmii2_txd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[3]]
set_property LOC AC13 [get_ports gmii2_txd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[4]]
set_property LOC AC12 [get_ports gmii2_txd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[5]]
set_property LOC AB12 [get_ports gmii2_txd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[6]]
set_property LOC AA14 [get_ports gmii2_txd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[7]]

set_property LOC AG15 [get_ports gmii2_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_tx_en]
set_property LOC AF14 [get_ports gmii2_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_tx_clk]
set_property LOC AB15 [get_ports gmii2_tx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_tx_er]

set_property LOC AF17 [get_ports gmii2_rxd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[0]]
set_property LOC AD15 [get_ports gmii2_rxd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[1]]
set_property LOC AH17 [get_ports gmii2_rxd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[2]]
set_property LOC AD14 [get_ports gmii2_rxd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[3]]
set_property LOC AK15 [get_ports gmii2_rxd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[4]]
set_property LOC AJ15 [get_ports gmii2_rxd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[5]]
set_property LOC AH14 [get_ports gmii2_rxd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[6]]
set_property LOC AG14 [get_ports gmii2_rxd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[7]]

set_property LOC AG17 [get_ports gmii2_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rx_clk]
set_property LOC AE17 [get_ports gmii2_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rx_dv]
set_property LOC AH13 [get_ports gmii2_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rx_er]

set_property LOC AD16 [get_ports mdio2_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports mdio2_mdio_io]
set_property LOC AE18 [get_ports mdio2_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio2_mdc]

set_property LOC AE13 [get_ports gmii2_gtx_in]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_gtx_in]
create_clock -name gmii2_gtx_in -period 8.0 [get_ports gmii2_gtx_in]

set_property LOC AF18 [get_ports gmii2_gtx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_gtx_clk]

#PLGE3
set_property LOC AB22 [get_ports clk_25M_out3]
set_property IOSTANDARD LVCMOS33 [get_ports clk_25M_out3]

set_property LOC AK21 [get_ports phy_rst_n3]
set_property IOSTANDARD LVCMOS33 [get_ports phy_rst_n3]

set_property LOC AH22 [get_ports gmii3_txd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_txd[0]]
set_property LOC AJ21 [get_ports gmii3_txd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_txd[1]]
set_property LOC AG22 [get_ports gmii3_txd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_txd[2]]
set_property LOC AJ20 [get_ports gmii3_txd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_txd[3]]
set_property LOC AH21 [get_ports gmii3_txd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_txd[4]]
set_property LOC AK20 [get_ports gmii3_txd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_txd[5]]
set_property LOC AJ19 [get_ports gmii3_txd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_txd[6]]
set_property LOC AH19 [get_ports gmii3_txd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_txd[7]]

set_property LOC AK22 [get_ports gmii3_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_tx_en]
set_property LOC AE22 [get_ports gmii3_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_tx_clk]
set_property LOC AG19 [get_ports gmii3_tx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_tx_er]

set_property LOC AC24 [get_ports gmii3_rxd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_rxd[0]]
set_property LOC AD24 [get_ports gmii3_rxd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_rxd[1]]
set_property LOC AE23 [get_ports gmii3_rxd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_rxd[2]]
set_property LOC AG25 [get_ports gmii3_rxd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_rxd[3]]
set_property LOC AF24 [get_ports gmii3_rxd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_rxd[4]]
set_property LOC AG24 [get_ports gmii3_rxd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_rxd[5]]
set_property LOC AH23 [get_ports gmii3_rxd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_rxd[6]]
set_property LOC AF23 [get_ports gmii3_rxd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_rxd[7]]

set_property LOC AG21 [get_ports gmii3_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_rx_clk]
set_property LOC AB24 [get_ports gmii3_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_rx_dv]
set_property LOC AJ23 [get_ports gmii3_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_rx_er]

set_property LOC AF19 [get_ports mdio3_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports mdio3_mdio_io]
set_property LOC AE21 [get_ports mdio3_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio3_mdc]

set_property LOC AD23 [get_ports gmii3_gtx_in]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_gtx_in]
create_clock -name gmii3_gtx_in -period 8.0 [get_ports gmii3_gtx_in]

set_property LOC AK17 [get_ports gmii3_gtx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii3_gtx_clk]

#PLGE4
set_property LOC P21 [get_ports clk_25M_out4]
set_property IOSTANDARD LVCMOS33 [get_ports clk_25M_out4]

set_property LOC P25 [get_ports phy_rst_n4]
set_property IOSTANDARD LVCMOS33 [get_ports phy_rst_n4]

set_property LOC U27 [get_ports gmii4_txd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_txd[0]]
set_property LOC P24 [get_ports gmii4_txd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_txd[1]]
set_property LOC P23 [get_ports gmii4_txd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_txd[2]]
set_property LOC V23 [get_ports gmii4_txd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_txd[3]]
set_property LOC R23 [get_ports gmii4_txd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_txd[4]]
set_property LOC V22 [get_ports gmii4_txd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_txd[5]]
set_property LOC U21 [get_ports gmii4_txd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_txd[6]]
set_property LOC U22 [get_ports gmii4_txd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_txd[7]]

set_property LOC W26 [get_ports gmii4_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_tx_en]
set_property LOC R25 [get_ports gmii4_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_tx_clk]
set_property LOC T22 [get_ports gmii4_tx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_tx_er]

set_property LOC T30 [get_ports gmii4_rxd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_rxd[0]]
set_property LOC T29 [get_ports gmii4_rxd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_rxd[1]]
set_property LOC T28 [get_ports gmii4_rxd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_rxd[2]]
set_property LOC U30 [get_ports gmii4_rxd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_rxd[3]]
set_property LOC U29 [get_ports gmii4_rxd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_rxd[4]]
set_property LOC W30 [get_ports gmii4_rxd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_rxd[5]]
set_property LOC V29 [get_ports gmii4_rxd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_rxd[6]]
set_property LOC W29 [get_ports gmii4_rxd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_rxd[7]]

set_property LOC R27 [get_ports gmii4_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_rx_clk]
set_property LOC T27 [get_ports gmii4_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_rx_dv]
set_property LOC W28 [get_ports gmii4_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_rx_er]

set_property LOC R21 [get_ports mdio4_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports mdio4_mdio_io]
set_property LOC R22 [get_ports mdio4_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio4_mdc]

set_property LOC U25 [get_ports gmii4_gtx_in]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_gtx_in]
create_clock -name gmii4_gtx_in -period 8.0 [get_ports gmii4_gtx_in]

set_property LOC W24 [get_ports gmii4_gtx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii4_gtx_clk]

#PLGE5
#set_property LOC T25 [get_ports clk_25M_out5]
#set_property IOSTANDARD LVCMOS33 [get_ports clk_25M_out5]

#set_property LOC AD25 [get_ports phy_rst_n5]
#set_property IOSTANDARD LVCMOS33 [get_ports phy_rst_n5]

#set_property LOC W23 [get_ports gmii5_txd[0]]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_txd[0]]
#set_property LOC Y23 [get_ports gmii5_txd[1]]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_txd[1]]
#set_property LOC AA22 [get_ports gmii5_txd[2]]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_txd[2]]
#set_property LOC AC23 [get_ports gmii5_txd[3]]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_txd[3]]
#set_property LOC Y22 [get_ports gmii5_txd[4]]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_txd[4]]
#set_property LOC AC22 [get_ports gmii5_txd[5]]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_txd[5]]
#set_property LOC Y21 [get_ports gmii5_txd[6]]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_txd[6]]
#set_property LOC AB21 [get_ports gmii5_txd[7]]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_txd[7]]

#set_property LOC AK25 [get_ports gmii5_tx_en]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_tx_en]
#set_property LOC AF20 [get_ports gmii5_tx_clk]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_tx_clk]
#set_property LOC AC21 [get_ports gmii5_tx_er]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_tx_er]

#set_property LOC AA30 [get_ports gmii5_rxd[0]]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_rxd[0]]
#set_property LOC AA29 [get_ports gmii5_rxd[1]]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_rxd[1]]
#set_property LOC AE25 [get_ports gmii5_rxd[2]]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_rxd[2]]
#set_property LOC W25 [get_ports gmii5_rxd[3]]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_rxd[3]]
#set_property LOC AA27 [get_ports gmii5_rxd[4]]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_rxd[4]]
#set_property LOC Y26 [get_ports gmii5_rxd[5]]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_rxd[5]]
#set_property LOC Y25 [get_ports gmii5_rxd[6]]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_rxd[6]]
#set_property LOC Y30 [get_ports gmii5_rxd[7]]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_rxd[7]]

#set_property LOC AE28 [get_ports gmii5_rx_clk]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_rx_clk]
#set_property LOC AF25 [get_ports gmii5_rx_dv]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_rx_dv]
#set_property LOC AA25 [get_ports gmii5_rx_er]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_rx_er]

#set_property LOC V26 [get_ports mdio5_mdio_io]
#set_property IOSTANDARD LVCMOS33 [get_ports mdio5_mdio_io]
#set_property LOC T23 [get_ports mdio5_mdc]
#set_property IOSTANDARD LVCMOS33 [get_ports mdio5_mdc]

#set_property LOC U26 [get_ports gmii5_gtx_in]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_gtx_in]
#create_clock -name gmii5_gtx_in -period 8.0 [get_ports gmii5_gtx_in]

#set_property LOC AA23 [get_ports gmii5_gtx_clk]
#set_property IOSTANDARD LVCMOS33 [get_ports gmii5_gtx_clk]

#PL_SFP0
set_property LOC R8 [get_ports mgt0_in_clk_p]
set_property LOC R7 [get_ports mgt0_in_clk_n]
create_clock -name mgt0_clk_p -period 8.0 [get_ports mgt0_in_clk_p]

set_property LOC P2 [get_ports sfp0_txp]
set_property LOC P1 [get_ports sfp0_txn]
set_property LOC T6 [get_ports sfp0_rxp]
set_property LOC T5 [get_ports sfp0_rxn]
