#PLGE0
set_property PACKAGE_PIN AB17 [get_ports {clk_25M_out0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk_25M_out0[0]}]

set_property PACKAGE_PIN AF13 [get_ports {phy_rst_n0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {phy_rst_n0[0]}]

set_property PACKAGE_PIN AG12 [get_ports {gmii0_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii0_txd[0]}]
set_property PACKAGE_PIN AF12 [get_ports {gmii0_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii0_txd[1]}]
set_property PACKAGE_PIN AE12 [get_ports {gmii0_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii0_txd[2]}]
set_property PACKAGE_PIN AD13 [get_ports {gmii0_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii0_txd[3]}]
set_property PACKAGE_PIN AC13 [get_ports {gmii0_txd[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii0_txd[4]}]
set_property PACKAGE_PIN AC12 [get_ports {gmii0_txd[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii0_txd[5]}]
set_property PACKAGE_PIN AB12 [get_ports {gmii0_txd[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii0_txd[6]}]
set_property PACKAGE_PIN AA14 [get_ports {gmii0_txd[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii0_txd[7]}]

set_property PACKAGE_PIN AG15 [get_ports gmii0_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_tx_en]
set_property PACKAGE_PIN AF14 [get_ports gmii0_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_tx_clk]
set_property PACKAGE_PIN AB15 [get_ports gmii0_tx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_tx_er]

set_property PACKAGE_PIN AF17 [get_ports {gmii0_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii0_rxd[0]}]
set_property PACKAGE_PIN AD15 [get_ports {gmii0_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii0_rxd[1]}]
set_property PACKAGE_PIN AH17 [get_ports {gmii0_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii0_rxd[2]}]
set_property PACKAGE_PIN AD14 [get_ports {gmii0_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii0_rxd[3]}]
set_property PACKAGE_PIN AK15 [get_ports {gmii0_rxd[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii0_rxd[4]}]
set_property PACKAGE_PIN AJ15 [get_ports {gmii0_rxd[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii0_rxd[5]}]
set_property PACKAGE_PIN AH14 [get_ports {gmii0_rxd[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii0_rxd[6]}]
set_property PACKAGE_PIN AG14 [get_ports {gmii0_rxd[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii0_rxd[7]}]

set_property PACKAGE_PIN AG17 [get_ports gmii0_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_rx_clk]
set_property PACKAGE_PIN AE17 [get_ports gmii0_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_rx_dv]
set_property PACKAGE_PIN AH13 [get_ports gmii0_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_rx_er]

set_property PACKAGE_PIN AD16 [get_ports mdio0_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports mdio0_mdio_io]
set_property PACKAGE_PIN AE18 [get_ports mdio0_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio0_mdc]

set_property PACKAGE_PIN AF18 [get_ports gmii0_gtx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_gtx_clk]

set_property PACKAGE_PIN AE13 [get_ports gmii0_gtx_in]
set_property IOSTANDARD LVCMOS33 [get_ports gmii0_gtx_in]

#PLGE1
set_property PACKAGE_PIN AB22 [get_ports {clk_25M_out1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk_25M_out1[0]}]

set_property PACKAGE_PIN AK21 [get_ports {phy_rst_n1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {phy_rst_n1[0]}]

set_property PACKAGE_PIN AH22 [get_ports {gmii1_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii1_txd[0]}]
set_property PACKAGE_PIN AJ21 [get_ports {gmii1_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii1_txd[1]}]
set_property PACKAGE_PIN AG22 [get_ports {gmii1_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii1_txd[2]}]
set_property PACKAGE_PIN AJ20 [get_ports {gmii1_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii1_txd[3]}]
set_property PACKAGE_PIN AH21 [get_ports {gmii1_txd[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii1_txd[4]}]
set_property PACKAGE_PIN AK20 [get_ports {gmii1_txd[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii1_txd[5]}]
set_property PACKAGE_PIN AJ19 [get_ports {gmii1_txd[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii1_txd[6]}]
set_property PACKAGE_PIN AH19 [get_ports {gmii1_txd[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii1_txd[7]}]

set_property PACKAGE_PIN AK22 [get_ports gmii1_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_tx_en]
set_property PACKAGE_PIN AE22 [get_ports gmii1_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_tx_clk]
set_property PACKAGE_PIN AG19 [get_ports gmii1_tx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_tx_er]

set_property PACKAGE_PIN AC24 [get_ports {gmii1_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii1_rxd[0]}]
set_property PACKAGE_PIN AD24 [get_ports {gmii1_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii1_rxd[1]}]
set_property PACKAGE_PIN AE23 [get_ports {gmii1_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii1_rxd[2]}]
set_property PACKAGE_PIN AG25 [get_ports {gmii1_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii1_rxd[3]}]
set_property PACKAGE_PIN AF24 [get_ports {gmii1_rxd[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii1_rxd[4]}]
set_property PACKAGE_PIN AG24 [get_ports {gmii1_rxd[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii1_rxd[5]}]
set_property PACKAGE_PIN AH23 [get_ports {gmii1_rxd[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii1_rxd[6]}]
set_property PACKAGE_PIN AF23 [get_ports {gmii1_rxd[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii1_rxd[7]}]

set_property PACKAGE_PIN AG21 [get_ports gmii1_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rx_clk]
set_property PACKAGE_PIN AB24 [get_ports gmii1_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rx_dv]
set_property PACKAGE_PIN AJ23 [get_ports gmii1_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rx_er]

set_property PACKAGE_PIN AF19 [get_ports mdio1_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports mdio1_mdio_io]
set_property PACKAGE_PIN AE21 [get_ports mdio1_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio1_mdc]

set_property PACKAGE_PIN AK17 [get_ports gmii1_gtx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_gtx_clk]

set_property PACKAGE_PIN AD23 [get_ports gmii1_gtx_in]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_gtx_in]

#PLGE2
set_property PACKAGE_PIN P21 [get_ports {clk_25M_out2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk_25M_out2[0]}]

set_property PACKAGE_PIN P25 [get_ports {phy_rst_n2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {phy_rst_n2[0]}]

set_property PACKAGE_PIN U27 [get_ports {gmii2_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii2_txd[0]}]
set_property PACKAGE_PIN P24 [get_ports {gmii2_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii2_txd[1]}]
set_property PACKAGE_PIN P23 [get_ports {gmii2_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii2_txd[2]}]
set_property PACKAGE_PIN V23 [get_ports {gmii2_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii2_txd[3]}]
set_property PACKAGE_PIN R23 [get_ports {gmii2_txd[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii2_txd[4]}]
set_property PACKAGE_PIN V22 [get_ports {gmii2_txd[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii2_txd[5]}]
set_property PACKAGE_PIN U21 [get_ports {gmii2_txd[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii2_txd[6]}]
set_property PACKAGE_PIN U22 [get_ports {gmii2_txd[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii2_txd[7]}]

set_property PACKAGE_PIN W26 [get_ports gmii2_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_tx_en]
set_property PACKAGE_PIN R25 [get_ports gmii2_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_tx_clk]
set_property PACKAGE_PIN T22 [get_ports gmii2_tx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_tx_er]

set_property PACKAGE_PIN T30 [get_ports {gmii2_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii2_rxd[0]}]
set_property PACKAGE_PIN T29 [get_ports {gmii2_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii2_rxd[1]}]
set_property PACKAGE_PIN T28 [get_ports {gmii2_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii2_rxd[2]}]
set_property PACKAGE_PIN U30 [get_ports {gmii2_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii2_rxd[3]}]
set_property PACKAGE_PIN U29 [get_ports {gmii2_rxd[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii2_rxd[4]}]
set_property PACKAGE_PIN W30 [get_ports {gmii2_rxd[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii2_rxd[5]}]
set_property PACKAGE_PIN V29 [get_ports {gmii2_rxd[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii2_rxd[6]}]
set_property PACKAGE_PIN W29 [get_ports {gmii2_rxd[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gmii2_rxd[7]}]

set_property PACKAGE_PIN R27 [get_ports gmii2_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rx_clk]
set_property PACKAGE_PIN T27 [get_ports gmii2_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rx_dv]
set_property PACKAGE_PIN W28 [get_ports gmii2_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rx_er]

set_property PACKAGE_PIN R21 [get_ports mdio2_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports mdio2_mdio_io]
set_property PACKAGE_PIN R22 [get_ports mdio2_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio2_mdc]

set_property PACKAGE_PIN W24 [get_ports gmii2_gtx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_gtx_clk]

set_property PACKAGE_PIN U25 [get_ports gmii2_gtx_in]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_gtx_in]

#PL_SFP0
set_property PACKAGE_PIN W8 [get_ports mgt0_in_clk_p]
set_property PACKAGE_PIN W7 [get_ports mgt0_in_clk_n]

set_property PACKAGE_PIN Y5 [get_ports sfp0_rxn]
set_property PACKAGE_PIN Y6 [get_ports sfp0_rxp]
set_property PACKAGE_PIN W3 [get_ports sfp0_txn]
set_property PACKAGE_PIN W4 [get_ports sfp0_txp]

#PL_SFP1
set_property PACKAGE_PIN AC3 [get_ports sfp1_rxn]
set_property PACKAGE_PIN AC4 [get_ports sfp1_rxp]
set_property PACKAGE_PIN AB1 [get_ports sfp1_txn]
set_property PACKAGE_PIN AB2 [get_ports sfp1_txp]

set_property PACKAGE_PIN AJ16 [get_ports {sfp0_disable_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sfp0_disable_out[0]}]
set_property PACKAGE_PIN AK16 [get_ports {sfp1_disable_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sfp1_disable_out[0]}]

#UART0
set_property PACKAGE_PIN Y20 [get_ports uart0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart0_rxd]
set_property PACKAGE_PIN AA20 [get_ports uart0_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart0_txd]

