#PLGE1
set_property LOC AB26 [get_ports clk_25M_out1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_25M_out1]

set_property LOC AK27 [get_ports phy_rst_n1]
set_property IOSTANDARD LVCMOS33 [get_ports phy_rst_n1]

set_property LOC AF28 [get_ports gmii1_txd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[0]]
set_property LOC AK28 [get_ports gmii1_txd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[1]]
set_property LOC AJ28 [get_ports gmii1_txd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[2]]
set_property LOC AK26 [get_ports gmii1_txd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[3]]
set_property LOC AJ26 [get_ports gmii1_txd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[4]]
set_property LOC AH26 [get_ports gmii1_txd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[5]]
set_property LOC AE26 [get_ports gmii1_txd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[6]]
set_property LOC AD26 [get_ports gmii1_txd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_txd[7]]

set_property LOC AH27 [get_ports gmii1_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_tx_en]
set_property LOC AC28 [get_ports gmii1_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_tx_clk]
set_property LOC AC27 [get_ports gmii1_tx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_tx_er]

set_property LOC AD30 [get_ports gmii1_rxd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[0]]
set_property LOC AD29 [get_ports gmii1_rxd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[1]]
set_property LOC AE30 [get_ports gmii1_rxd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[2]]
set_property LOC AD28 [get_ports gmii1_rxd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[3]]
set_property LOC AF29 [get_ports gmii1_rxd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[4]]
set_property LOC AF30 [get_ports gmii1_rxd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[5]]
set_property LOC AH29 [get_ports gmii1_rxd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[6]]
set_property LOC AJ30 [get_ports gmii1_rxd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rxd[7]]

set_property LOC AE27 [get_ports gmii1_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rx_clk]
set_property LOC AB30 [get_ports gmii1_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rx_dv]
set_property LOC AJ29 [get_ports gmii1_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_rx_er]

set_property LOC AC29 [get_ports mdio1_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports mdio1_mdio_io]
set_property LOC AC26 [get_ports mdio1_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio1_mdc]

set_property LOC AB27 [get_ports gmii1_gtx_in]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_gtx_in]
create_clock -name gmii1_gtx_in -period 8.0 [get_ports gmii1_gtx_in]

set_property LOC AG26 [get_ports gmii1_gtx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii1_gtx_clk]

#PLGE2
set_property LOC AB17 [get_ports clk_25M_out2]
set_property IOSTANDARD LVCMOS33 [get_ports clk_25M_out2]

set_property LOC AF13 [get_ports phy_rst_n2]
set_property IOSTANDARD LVCMOS33 [get_ports phy_rst_n2]

set_property LOC AG12 [get_ports gmii2_txd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[0]]
set_property LOC AF12 [get_ports gmii2_txd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[1]]
set_property LOC AE12 [get_ports gmii2_txd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[2]]
set_property LOC AD13 [get_ports gmii2_txd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[3]]
set_property LOC AC13 [get_ports gmii2_txd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[4]]
set_property LOC AC12 [get_ports gmii2_txd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[5]]
set_property LOC AB12 [get_ports gmii2_txd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[6]]
set_property LOC AA14 [get_ports gmii2_txd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_txd[7]]

set_property LOC AG15 [get_ports gmii2_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_tx_en]
set_property LOC AF14 [get_ports gmii2_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_tx_clk]
set_property LOC AB15 [get_ports gmii2_tx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_tx_er]

set_property LOC AF17 [get_ports gmii2_rxd[0]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[0]]
set_property LOC AD15 [get_ports gmii2_rxd[1]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[1]]
set_property LOC AH17 [get_ports gmii2_rxd[2]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[2]]
set_property LOC AD14 [get_ports gmii2_rxd[3]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[3]]
set_property LOC AK15 [get_ports gmii2_rxd[4]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[4]]
set_property LOC AJ15 [get_ports gmii2_rxd[5]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[5]]
set_property LOC AH14 [get_ports gmii2_rxd[6]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[6]]
set_property LOC AG14 [get_ports gmii2_rxd[7]]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rxd[7]]

set_property LOC AG17 [get_ports gmii2_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rx_clk]
set_property LOC AE17 [get_ports gmii2_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rx_dv]
set_property LOC AH13 [get_ports gmii2_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_rx_er]

set_property LOC AD16 [get_ports mdio2_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports mdio2_mdio_io]
set_property LOC AE18 [get_ports mdio2_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio2_mdc]

set_property LOC AE13 [get_ports gmii2_gtx_in]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_gtx_in]
create_clock -name gmii2_gtx_in -period 8.0 [get_ports gmii2_gtx_in]

set_property LOC AF18 [get_ports gmii2_gtx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports gmii2_gtx_clk]

#PL_SFP0
set_property LOC AC8 [get_ports mgt0_in_clk_p]
set_property LOC AC7 [get_ports mgt0_in_clk_n]
create_clock -name mgt0_clk_p -period 8.0 [get_ports mgt0_in_clk_p]

set_property LOC AH2 [get_ports sfp0_txp]
set_property LOC AH1 [get_ports sfp0_txn]
set_property LOC AH6 [get_ports sfp0_rxp]
set_property LOC AH5 [get_ports sfp0_rxn]

set_property LOC AJ16 [get_ports sfp0_en_out]
set_property IOSTANDARD LVCMOS33 [get_ports sfp0_en_out]
set_property LOC AK16 [get_ports sfp1_en_out]
set_property IOSTANDARD LVCMOS33 [get_ports sfp1_en_out]
